[platformio]
default_envs = release
globallib_dir = lib      ;
workspace_dir = piobuild ;

[env]
platform = ststm32
board = genericSTM32F103VD
framework = cmsis
upload_protocol = stlink
debug_tool = stlink

platform_packages =
    toolchain-gccarmnoneeabi@~1.120301.0

[env:release]

extra_scripts = pre:build_flags_release.py 


[env:debug]

build_type = debug
extra_scripts = pre:build_flags_debug.py 
